### ISSUE TITLE
You can change complete template but save the content of website.

### ISSUE THREAD

**Issue by mindexpert7546** [mindexpert7546/Blog_for_switch_into_Linux#1]
**You can change complete template but save the content of website.** 

Guys here i hava create the a small blog website with the help of html and css. I am going to assign the website to you , you can change its template but keep the content for this website , I hope you will work on them , Thank you : )

**Comment by abel-otegbola** [comment]
Hi @mindexpert7546  
Can you assign this to me.

**Comment by mindexpert7546** [comment]
Yeah sure  @abel-otegbola

**Comment by abel-otegbola** [comment]
Alright. You can assign it to me.

**Comment by mindexpert7546** [comment]
Yeah sure thank to for that  @abel-otegbola
